config/routes.rb
Rails.application.routes.draw do
  get 'item/new'

  resources :lists

  root 'lists#index'

  get '/items/:id/' => 'items#show', :as => :item
  delete '/items/:id' => 'item#destroy'

  post 'item/new' => 'item#create'

  resources :item

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :list, foreign_key: "list_title"

end

app/models/list.rb
class List < ActiveRecord::Base

  has_many :list_items, foreign_key: "list_title"

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base

  #this model is only used for an explicit relationship

  belongs_to :list
  belongs_to :item

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  $current_list

  def new
    @list_title = params[:list_title]
    @actual_list = List.find_by_title(@list_title)
    $current_list = @actual_list
  end

  def create
    @item = Item.new(item_params)

    @item.save
    redirect_to list_path(List.find_by_title($current_list.title), :list_title => $current_list.title)
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.present?
      @item.destroy
    end
    redirect_to :back
  end

  private
    def item_params
      params.require(:item).permit(:name, :list_title)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @items = Item.where("list_title = ?", params[:list_title])
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_path(@list, :list_title => @list.title), notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    # First delete all items associated with the list we wish to destroy
    Item.where(list_title: @list.title).delete_all
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/item/new.html.erb
<h3>New Item for <%= @actual_list.title %></h3>

<%= form_for :item do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :list_title %><br />
    <%= f.text_field :list_title, :value => @list_title %>
  </p>

  <p>
    <%= link_to 'Back', list_path(@actual_list), class: 'btn btn-danger btn-xs' %>
    <%= f.submit %>
  </p> 
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<br />

<%= link_to 'Back', list_path(@list, :list_title => @list.title), class: 'btn btn-warning btn-xs' %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Here are your lists.</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= link_to 'Show', list_path(list, :list_title => list.title), class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_list_path(list), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_list_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New List
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<br />

<%= link_to 'Back', lists_path, class: 'btn btn-warning btn-xs' %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<table>
  <thead>
    <tr>
      <th>Items</th>
    </tr>
  </thead>

  <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= link_to 'Delete', item_path(item, :list => @list), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs' %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Item', new_item_path(:list_title => @list.title, :list_id => @list.id), class: 'btn btn-success btn-xs' %> |
<%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-info btn-xs' %> |
<%= link_to 'Back', lists_path, class: 'btn btn-warning btn-xs' %>